#pragma once
#include "Core.h"
#include "CoreUObject.h"
#include "Engine/Engine.h"
#include "Engine/EngineTypes.h"
#include "SlateCore.h"
#include "SlateBasics.h"
#include "ModuleManager.h"

DECLARE_LOG_CATEGORY_EXTERN(QuestsEditor, All, All)
class FQuestsEditorModule : public IModuleInterface
{
public:
	virtual void StartupModule() override;
	virtual void ShutdownModule() override;
private:
	void PrepareGeneratedBlueprintEvents();

#define RegisterDefaultEvent(Class, FuncName) \
(FKismetEditorUtilities::RegisterAutoGeneratedDefaultEvent(this, Class::StaticClass(), GET_FUNCTION_NAME_CHECKED(Class, FuncName)))


};